// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rooms.API.Data;

namespace Rooms.API.Migrations
{
    [DbContext(typeof(_AppContext))]
    partial class _AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rooms.API.Data.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LevelOfDifficulty")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("LevelOfFear")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<int>("MinCountGamers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasMaxLength(5)
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "New York",
                            Company = "Intercity",
                            Description = "Think you’ve got what it takes to be the world’s greatest thief?",
                            Duration = "60m",
                            LevelOfDifficulty = 3,
                            LevelOfFear = 1,
                            MinAge = 12,
                            MinCountGamers = 1,
                            Name = "DIAMOND HEIST",
                            PhoneNumber = "0123456789",
                            PictureUrl = "https://m.economictimes.com/thumb/msid-60217597,width-1200,height-900,resizemode-4,imgsize-73839/the-untold-story-of-a-100mn-diamond-heist-and-how-it-happened.jpg",
                            Rating = 1.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "St. Lois",
                            Company = "King",
                            Description = "Can you save the kingdom from eternal darkness?",
                            Duration = "60m",
                            LevelOfDifficulty = 5,
                            LevelOfFear = 1,
                            MinAge = 10,
                            MinCountGamers = 5,
                            Name = "CURSED CASTLE",
                            PhoneNumber = "213456789",
                            PictureUrl = "https://images-na.ssl-images-amazon.com/images/I/91hTjrrFYIL.jpg",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "New York",
                            Company = "King",
                            Description = "Will you survive the trials of a Secret Society’s initiation?",
                            Duration = "120m",
                            LevelOfDifficulty = 4,
                            LevelOfFear = 3,
                            MinAge = 16,
                            MinCountGamers = 5,
                            Name = "SECRET SOCIETY",
                            PhoneNumber = "123456789",
                            PictureUrl = "https://upload.wikimedia.org/wikipedia/commons/2/24/Secret_Society_Buildings_New_Haven.jpg",
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "St. Lois",
                            Company = "King",
                            Description = "Can you save the Mona Lisa from burglars?",
                            Duration = "80m",
                            LevelOfDifficulty = 2,
                            LevelOfFear = 1,
                            MinAge = 10,
                            MinCountGamers = 2,
                            Name = "DAVINCI’S WORKSHOP",
                            PhoneNumber = "123456789",
                            PictureUrl = "https://i.pinimg.com/originals/32/35/b0/3235b03626e8bf3baf3accd7399df06c.jpg",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Chicago",
                            Company = "King",
                            Description = "Ready to defend your home from the Wet Bandits?",
                            Duration = "60m",
                            LevelOfDifficulty = 5,
                            LevelOfFear = 4,
                            MinAge = 10,
                            MinCountGamers = 4,
                            Name = "HOME ALONE",
                            PhoneNumber = "987654310",
                            PictureUrl = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWCBy0UhjPAQW8vS-Iif6T6g371tYQktlEPQ&usqp=CAU",
                            Rating = 5.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
